# These are supported funding model platforms

github:  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: TheSuperSanya # Replace with a single Patreon username
open_collective: TheSuperSanya # Replace with a single Open Collective username
ko_fi: TheSuperSanya # Replace with a single Ko-fi username
tidelift: TheSuperSanya # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: TheSuperSanya # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: TheSuperSanya # Replace with a single Liberapay username
issuehunt: TheSuperSanya # Replace with a single IssueHunt username
otechie: TheSuperSanya # Replace with a single Otechie username
custom: plspetdoge.com # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
